# Generated by Django 5.0.7 on 2024-08-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='amount',
        ),
    ]
